"""Prints the Swift block with the COMPACT stone geometry (used for the menu bar icon in Brasa.swift).
Run: python3 generate_stone_swift.py, then paste the output over the `enum Stone` block."""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
import veins
from coal import SILHOUETTE
x0, y0, x1, y1 = SILHOUETTE.bounds

def rings(g):
    out = []
    for p in (list(g.geoms) if hasattr(g, "geoms") else [g]):
        if p.geom_type != "Polygon" or p.is_empty: continue
        p = p.simplify(0.35)
        for r in [p.exterior, *p.interiors]: out.append([round(v, 1) for xy in list(r.coords)[:-1] for v in xy])
    return out
fmt = lambda L: "[" + ",\n    ".join("[" + ",".join(f"{v:g}" for v in a) + "]" for a in L) + "]"
print(f"""// ───────── the brand stone (compact version, generated by brand/generate_stone_swift.py; do not edit by hand) ─────────
enum Stone {{
  static let box = CGRect(x: {x0:.1f}, y: {y0:.1f}, width: {x1-x0:.1f}, height: {y1-y0:.1f})
  static let base: [[CGFloat]] = {fmt(rings(veins.COMPACT[0][0]))}
  static let ember: [[CGFloat]] = {fmt(rings(veins.COMPACT[1][0]))}
  static func path(_ rings: [[CGFloat]], in r: NSRect) -> NSBezierPath {{
    let k = min(r.width / box.width, r.height / box.height)
    let ox = r.midX - box.midX * k, oy = r.midY + box.midY * k
    let p = NSBezierPath(); p.windingRule = .evenOdd
    for ring in rings {{
      for i in stride(from: 0, to: ring.count, by: 2) {{
        let pt = NSPoint(x: ox + ring[i] * k, y: oy - ring[i + 1] * k)
        if i == 0 {{ p.move(to: pt) }} else {{ p.line(to: pt) }}
      }}
      p.close()
    }}
    return p
  }}
  /// the stone (light enough to show on a dark menu bar) with the ember in the state's color
  static func draw(in r: NSRect, ember color: NSColor) {{
    let dark = NSAppearance.currentDrawing().bestMatch(from: [.darkAqua, .aqua]) == .darkAqua
    (dark ? NSColor(red: 0.36, green: 0.36, blue: 0.39, alpha: 1) : NSColor(red: 0.055, green: 0.05, blue: 0.05, alpha: 1)).setFill()
    path(base, in: r).fill()
    color.setFill(); path(ember, in: r).fill()
  }}
}}
""")
