# Site copy in English (en), Brazilian Portuguese (pt) and Spanish (es). To add a language, copy a block and translate it.
T = {
 "en": dict(
  path="/", lang="en", html="en", nome="English",
  title="Brasa: free Mac menu bar temperature monitor for Apple Silicon (no sudo)",
  desc="Brasa is a free, open-source menu bar app that monitors your Mac's chip, battery and SSD temperature, memory pressure and fans on Apple Silicon (M1 to M4), and warns you before it overheats. No sudo, no telemetry.",
  h1="Know when your Mac is too hot, before it slows down.",
  lead="Brasa is a light menu bar app for Apple Silicon Macs. It watches the chip, battery and SSD temperature, memory pressure, fans and the macOS thermal state, and tells you in plain words when to stop a heavy job.",
  cta1="View on GitHub", cta2="How it works", nav=["Features", "How it works", "FAQ", "Support"],
  feat_h="A temperature monitor that tells you what to do",
  feats=[("Real chip temperature, no sudo", "Reads the Apple Silicon sensors in-process through IOKit. No terminal commands, no admin password, no helper tool."),
         ("Four clear states", "Safe, warming up, too hot, critical. The stone in the menu bar changes color, and the panel explains the risk and the next step."),
         ("Your limits, not ours", "Defaults are 85, 92 and 100 °C for the chip. Change them in Settings; thresholds keep their order and each one resets to its default."),
         ("More than the chip", "Battery and SSD temperature, memory pressure and swap, CPU and GPU load, fan speed, and the top processes heating the Mac."),
         ("Smart notifications", "Alerts when the level changes and when it cools down, with a cool-down margin so it does not nag you at the edge of a limit."),
         ("Light and private", "About 1% of one CPU core and ~55 MB of memory, read every 2 seconds. It makes no network requests and sends no data.")],
  how_h="How it works", how_p="Brasa turns raw temperatures into four levels. The color of the stone is the status, at a glance, in the menu bar.",
  levels=[("Safe", "#33CC80", "Everything within normal range."), ("Warming up", "#FFB533", "Chip above 85 °C. Avoid starting a render or export."),
          ("Too hot", "#FF7A29", "Chip above 92 °C. Pause heavy work until it drops below 80 °C."), ("Critical", "#FF4052", "Chip above 100 °C or macOS is throttling hard. Close what is heavy now.")],
  shot_alt="Brasa panel showing 42 °C chip temperature, a 10-minute graph, battery, memory and SSD cards",
  faq_h="Frequently asked questions",
  faq=[("Does Brasa need sudo or admin rights?", "No. It reads the sensors directly from the app, so there is no password prompt and no privileged helper."),
       ("Which Macs does it support?", "Apple Silicon Macs (M1 to M4) on macOS 14 or later. It is developed on a MacBook Pro with M4 Pro; sensor names can vary between chips, so reports from other models are welcome. Intel Macs are not supported."),
       ("Can it control my fans?", "No. Brasa is a monitor: it shows fan speed and warns you, but it does not change fan curves."),
       ("Is it free and open source?", "Yes. The source is on GitHub under the MIT license. If it helps you, you can support the project."),
       ("Does it collect data or use the internet?", "No. Everything runs locally. The app makes no network requests and has no analytics."),
       ("How is it different from other Mac monitors?", "Brasa focuses on safety: it turns temperatures into clear states with advice, keeps your own thresholds, and stays light. For full hardware dashboards or fan control, other tools are a better fit.")],
  sup_h="Support the project", sup_p="Brasa is free and open source. If it saved you from a hot Mac, you can help keep it going.",
  foot="Made in Brazil by Renato Alves.", gh="Source on GitHub", soon="Notarized download coming soon. For now, build it in one command (see the README).",
  kw="mac temperature monitor, menu bar temperature, apple silicon temperature, m4 mac temperature monitor, macbook overheating, cpu temperature mac, mac thermal monitor, mac fan speed, no sudo"),
 "pt": dict(
  path="/pt/", lang="pt-BR", html="pt-BR", nome="Português",
  title="Brasa: monitor de temperatura do Mac na barra de menus, grátis (Apple Silicon, sem sudo)",
  desc="Brasa é um app gratuito e de código aberto para a barra de menus que monitora a temperatura do chip, da bateria e do SSD, a memória e as ventoinhas do Mac Apple Silicon (M1 a M4) e avisa antes de superaquecer. Sem sudo, sem telemetria.",
  h1="Saiba quando o seu Mac está quente demais, antes de ele travar.",
  lead="Brasa é um app leve de barra de menus para Macs Apple Silicon. Ele vigia a temperatura do chip, da bateria e do SSD, a memória, as ventoinhas e o estado térmico do macOS, e diz em palavras simples a hora de parar um trabalho pesado.",
  cta1="Ver no GitHub", cta2="Como funciona", nav=["Recursos", "Como funciona", "Perguntas", "Apoie"],
  feat_h="Um monitor de temperatura que diz o que fazer",
  feats=[("Temperatura real do chip, sem sudo", "Lê os sensores do Apple Silicon dentro do próprio app, via IOKit. Sem comando no terminal, sem senha de administrador."),
         ("Quatro estados claros", "Seguro, esquentando, quente demais e crítico. A pedra na barra de menus muda de cor e o painel explica o risco e o que fazer."),
         ("Seus limites, não os nossos", "Os padrões do chip são 85, 92 e 100 °C. Mude em Ajustes: os limites mantêm a ordem e cada um volta ao padrão."),
         ("Mais que o chip", "Temperatura da bateria e do SSD, pressão de memória e swap, uso de CPU e GPU, ventoinhas e os processos que mais esquentam."),
         ("Notificações inteligentes", "Avisa quando o nível muda e quando esfria, com margem de resfriamento para não ficar insistindo no limite."),
         ("Leve e privado", "Cerca de 1% de um núcleo e ~55 MB de memória, lendo a cada 2 segundos. Não faz nenhuma requisição de rede nem envia dados.")],
  how_h="Como funciona", how_p="A Brasa transforma temperaturas brutas em quatro níveis. A cor da pedra é o status, num relance, na barra de menus.",
  levels=[("Seguro", "#33CC80", "Tudo dentro do normal."), ("Esquentando", "#FFB533", "Chip acima de 85 °C. Evite começar render ou exportação."),
          ("Quente demais", "#FF7A29", "Chip acima de 92 °C. Pause o trabalho pesado até baixar de 80 °C."), ("Crítico", "#FF4052", "Chip acima de 100 °C ou o macOS reduzindo a velocidade. Feche o que pesa agora.")],
  shot_alt="Painel da Brasa mostrando 42 °C no chip, gráfico de 10 minutos e cartões de bateria, memória e SSD",
  faq_h="Perguntas frequentes",
  faq=[("A Brasa precisa de sudo ou senha de administrador?", "Não. Ela lê os sensores direto do app, então não há pedido de senha nem ferramenta com privilégios."),
       ("Quais Macs são suportados?", "Macs Apple Silicon (M1 a M4) com macOS 14 ou mais novo. Foi desenvolvida num MacBook Pro com M4 Pro; os nomes dos sensores podem variar entre chips, então relatos de outros modelos são bem-vindos. Macs Intel não são suportados."),
       ("Ela controla as ventoinhas?", "Não. A Brasa é um monitor: mostra a rotação e avisa, mas não altera a curva das ventoinhas."),
       ("É grátis e de código aberto?", "Sim. O código está no GitHub sob licença MIT. Se ajudar você, pode apoiar o projeto."),
       ("Ela coleta dados ou usa a internet?", "Não. Tudo roda localmente. O app não faz requisições de rede e não tem analytics."),
       ("Qual a diferença para outros monitores de Mac?", "A Brasa foca em segurança: transforma temperaturas em estados claros com orientação, guarda os seus limites e é leve. Para painéis completos de hardware ou controle de ventoinhas, outras ferramentas servem melhor.")],
  sup_h="Apoie o projeto", sup_p="A Brasa é gratuita e de código aberto. Se ela livrou você de um Mac superaquecido, ajude a manter o projeto vivo.",
  foot="Feito no Brasil por Renato Alves.", gh="Código no GitHub", soon="Download notarizado em breve. Por enquanto, compile com um comando (veja o README).",
  kw="monitor de temperatura mac, temperatura barra de menus, temperatura apple silicon, mac m4 temperatura, macbook esquentando, temperatura cpu mac, ventoinha mac, sem sudo"),
 "es": dict(
  path="/es/", lang="es", html="es", nome="Español",
  title="Brasa: monitor de temperatura para Mac en la barra de menús, gratis (Apple Silicon, sin sudo)",
  desc="Brasa es una app gratuita y de código abierto para la barra de menús que vigila la temperatura del chip, la batería y el SSD, la memoria y los ventiladores de tu Mac Apple Silicon (M1 a M4) y te avisa antes de que se sobrecaliente. Sin sudo, sin telemetría.",
  h1="Sabe cuándo tu Mac está demasiado caliente, antes de que se ralentice.",
  lead="Brasa es una app ligera de barra de menús para Macs Apple Silicon. Vigila la temperatura del chip, la batería y el SSD, la memoria, los ventiladores y el estado térmico de macOS, y te dice con palabras sencillas cuándo parar un trabajo pesado.",
  cta1="Ver en GitHub", cta2="Cómo funciona", nav=["Funciones", "Cómo funciona", "Preguntas", "Apoya"],
  feat_h="Un monitor de temperatura que te dice qué hacer",
  feats=[("Temperatura real del chip, sin sudo", "Lee los sensores del Apple Silicon dentro de la propia app, mediante IOKit. Sin comandos en la terminal ni contraseña de administrador."),
         ("Cuatro estados claros", "Seguro, calentándose, demasiado caliente y crítico. La piedra de la barra de menús cambia de color y el panel explica el riesgo y el siguiente paso."),
         ("Tus límites, no los nuestros", "Los valores por defecto del chip son 85, 92 y 100 °C. Cámbialos en Ajustes: los límites mantienen su orden y cada uno puede volver a su valor por defecto."),
         ("Más que el chip", "Temperatura de la batería y del SSD, presión de memoria y swap, uso de CPU y GPU, ventiladores y los procesos que más calientan."),
         ("Notificaciones inteligentes", "Avisa cuando cambia el nivel y cuando se enfría, con un margen de enfriamiento para no insistir en el borde del límite."),
         ("Ligera y privada", "Alrededor de un 1% de un núcleo y ~55 MB de memoria, leyendo cada 2 segundos. No hace ninguna petición de red ni envía datos.")],
  how_h="Cómo funciona", how_p="Brasa convierte temperaturas en bruto en cuatro niveles. El color de la piedra es el estado, de un vistazo, en la barra de menús.",
  levels=[("Seguro", "#33CC80", "Todo dentro de lo normal."), ("Calentándose", "#FFB533", "Chip por encima de 85 °C. Evita empezar un render o una exportación."),
          ("Demasiado caliente", "#FF7A29", "Chip por encima de 92 °C. Pausa el trabajo pesado hasta que baje de 80 °C."), ("Crítico", "#FF4052", "Chip por encima de 100 °C o macOS reduciendo mucho la velocidad. Cierra ahora lo que pesa.")],
  shot_alt="Panel de Brasa con el chip a 42 °C, gráfico de 10 minutos y tarjetas de batería, memoria y SSD",
  faq_h="Preguntas frecuentes",
  faq=[("¿Brasa necesita sudo o permisos de administrador?", "No. Lee los sensores directamente desde la app, así que no hay petición de contraseña ni herramienta con privilegios."),
       ("¿Qué Macs son compatibles?", "Macs Apple Silicon (M1 a M4) con macOS 14 o posterior. Se desarrolla en un MacBook Pro con M4 Pro; los nombres de los sensores pueden variar entre chips, así que los informes de otros modelos son bienvenidos. Los Macs Intel no son compatibles."),
       ("¿Puede controlar mis ventiladores?", "No. Brasa es un monitor: muestra la velocidad de los ventiladores y avisa, pero no cambia sus curvas."),
       ("¿Es gratis y de código abierto?", "Sí. El código está en GitHub con licencia MIT. Si te ayuda, puedes apoyar el proyecto."),
       ("¿Recopila datos o usa internet?", "No. Todo se ejecuta en local. La app no hace peticiones de red y no tiene analíticas."),
       ("¿En qué se diferencia de otros monitores de Mac?", "Brasa se centra en la seguridad: convierte las temperaturas en estados claros con consejos, respeta tus propios límites y es ligera. Para paneles completos de hardware o control de ventiladores, otras herramientas encajan mejor.")],
  sup_h="Apoya el proyecto", sup_p="Brasa es gratuita y de código abierto. Si te libró de un Mac sobrecalentado, ayuda a mantenerla viva.",
  foot="Hecho en Brasil por Renato Alves.", gh="Código en GitHub", soon="Descarga notarizada próximamente. Por ahora, compílala con un comando (consulta el README).",
  kw="monitor de temperatura mac, temperatura barra de menús, temperatura apple silicon, mac m4 temperatura, macbook sobrecalentamiento, temperatura cpu mac, ventiladores mac, sin sudo"),
}


# Layout copy: section labels, hero stats, limits, support.
X = {
 "en": dict(
  kicker="Mac temperature monitor", tagline="Know when your Mac is too hot.",
  nav=["Features", "How it works", "Limits", "FAQ", "Support"], theme=["Auto", "Dark", "Light"],
  stats=[(4, "", "", "levels, one color each"), (1, "≈", "%", "of one CPU core"), (0, "", "", "network requests"), (3, "", "", "languages")],
  idle="All safe", busy="Warming up…",
  s1="Features", t1="A monitor that tells you <em>what to do</em>.", d1="Numbers are easy to ignore. Brasa turns them into a state, a reason and a next step.",
  s2="How it works", t2="Four levels, <em>one stone</em>.", d2="The stone in the menu bar changes color with the state of your Mac. Open it for the reason and the numbers behind it.",
  s3="Limits", t3="Your limits, <em>not ours</em>.", d3="These are only the defaults. In Settings you change every threshold; they keep their order and each one can go back to its default.",
  lim=[("85 / 92 / 100", "°C", "Chip: warn, pause, critical"), ("40 / 45", "°C", "Battery: warn, high"), ("70 / 80", "°C", "SSD: warn, high"), ("8", "GB", "Swap: warn")],
  s4="FAQ", t4="Quick <em>answers</em>.", s5="Support", t5="Keep it <em>going</em>.",
  kofi="Support on Ko-fi", badge_open="Open source · MIT", fine="Free forever. Built in Brazil.",
  alt_mark="Brasa: a piece of black coal with glowing ember veins", alt_lang="Language"),
 "pt": dict(
  kicker="Monitor de temperatura do Mac", tagline="Saiba quando o seu Mac está quente demais.",
  nav=["Recursos", "Como funciona", "Limites", "Perguntas", "Apoie"], theme=["Auto", "Escuro", "Claro"],
  stats=[(4, "", "", "níveis, uma cor cada"), (1, "≈", "%", "de um núcleo de CPU"), (0, "", "", "requisições de rede"), (3, "", "", "idiomas")],
  idle="Tudo seguro", busy="Esquentando…",
  s1="Recursos", t1="Um monitor que diz <em>o que fazer</em>.", d1="Número é fácil de ignorar. A Brasa transforma tudo em um estado, um motivo e o próximo passo.",
  s2="Como funciona", t2="Quatro níveis, <em>uma pedra</em>.", d2="A pedra na barra de menus muda de cor com o estado do Mac. Abra para ver o motivo e os números por trás.",
  s3="Limites", t3="Os seus limites, <em>não os nossos</em>.", d3="Estes são só os padrões. Em Ajustes você muda cada limite; eles mantêm a ordem e cada um volta ao padrão.",
  lim=[("85 / 92 / 100", "°C", "Chip: aviso, pausa, crítico"), ("40 / 45", "°C", "Bateria: aviso, alto"), ("70 / 80", "°C", "SSD: aviso, alto"), ("8", "GB", "Swap: aviso")],
  s4="Perguntas", t4="Respostas <em>rápidas</em>.", s5="Apoie", t5="Ajude a <em>manter</em>.",
  kofi="Apoie no Ko-fi", badge_open="Código aberto · MIT", fine="Grátis para sempre. Feito no Brasil.",
  alt_mark="Brasa: um pedaço de carvão preto com veios de brasa brilhando", alt_lang="Idioma"),
 "es": dict(
  kicker="Monitor de temperatura para Mac", tagline="Sabe cuándo tu Mac está demasiado caliente.",
  nav=["Funciones", "Cómo funciona", "Límites", "Preguntas", "Apoya"], theme=["Auto", "Oscuro", "Claro"],
  stats=[(4, "", "", "niveles, un color cada uno"), (1, "≈", "%", "de un núcleo de CPU"), (0, "", "", "peticiones de red"), (3, "", "", "idiomas")],
  idle="Todo seguro", busy="Calentándose…",
  s1="Funciones", t1="Un monitor que te dice <em>qué hacer</em>.", d1="Un número es fácil de ignorar. Brasa lo convierte en un estado, un motivo y el siguiente paso.",
  s2="Cómo funciona", t2="Cuatro niveles, <em>una piedra</em>.", d2="La piedra de la barra de menús cambia de color con el estado del Mac. Ábrela para ver el motivo y los números detrás.",
  s3="Límites", t3="Tus límites, <em>no los nuestros</em>.", d3="Estos son solo los valores por defecto. En Ajustes cambias cada límite; mantienen su orden y cada uno puede volver a su valor por defecto.",
  lim=[("85 / 92 / 100", "°C", "Chip: aviso, pausa, crítico"), ("40 / 45", "°C", "Batería: aviso, alto"), ("70 / 80", "°C", "SSD: aviso, alto"), ("8", "GB", "Swap: aviso")],
  s4="Preguntas", t4="Respuestas <em>rápidas</em>.", s5="Apoya", t5="Ayuda a <em>mantenerla</em>.",
  kofi="Apoya en Ko-fi", badge_open="Código abierto · MIT", fine="Gratis para siempre. Hecho en Brasil.",
  alt_mark="Brasa: un trozo de carbón negro con vetas de brasa brillando", alt_lang="Idioma"),
}
